### ISSUE TITLE
Mobile width viewport cuts off front of body

### ISSUE THREAD

**Issue by alexcarson440** [timmo001/system-bridge-website#238]
### Description

Pages such as the "Download & Install", "Running", and "CLI" are unreadable with a mobile-sized viewport because the start (and end) of the content is pushed out of the frame and there is no option to scroll horizontally. Please fix styling for these pages at smaller window sizes so that the instructions can be viewed from mobile.

### Additional information

I tested this on a pixel 5 which apparently has a width of 393 according to the Chrome Dev tools.

**Comment by alexcarson440** [comment]
This issue is still present on the current live website

**Comment by timmo001** [comment]
Fixed in 9306c17543c1bc654e948315a0adef2b0a77ef35

Thanks!
